### ISSUE TITLE
Not reading `.ghci` file?

### ISSUE THREAD

**Issue by andrewufrank** [rcook/ghci-helper#1]
I tried to use your `ghci-helper ` because it looks like a good idea and other tools seem not to work reliably. I use stack and have used stack exec `ghci` in vs code before; I had to set up a (relatively long)   `.ghci` file and it works well to start ghci with the test stanza from cabal. when I use `ghci-helper` it does not select the test stanza, but offers a selection (not including the test stanza). 
I have the impression that `ghci-helper` does not read the `.ghci` file. could you change this - then your tool would be very helpful!
thank you

**Comment by rcook** [comment]
@andrewufrank: I don't have time to maintain this tool at the moment. If you were to submit a patch to address this issue, I would be happy to incorporate it.

**Comment by andrewufrank** [comment]
I will experiment further to see what tools I really want to use. Thank you for your efforts so far - the idea is good but looking at the code, I am not certain if I really want to learn so much about vs code internals.
